name: digital_defenders_app
description: A Flutter app for cybersecurity awareness
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.1.1
  characters: 1.4.0
  crypto: ^3.0.6
  flutter_tts: ^4.2.3
  google_fonts: ^6.3.0
  http: ^1.4.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0

flutter:
  uses-material-design: true
